apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissajous-deployment
  labels:
    app: lissajous
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissajous
  template:
    metadata:
      labels:
        app: lissajous
    spec:
      containers:
      - name: lissajous-container
        image: glaut0n/lissajous-golang:1.2
        ports:
        - name: http-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: http-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http-port
          initialDelaySeconds: 15
          timeoutSeconds: 30