apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissajous-deployment
  labels:
    app: lissajous
spec:
  replicas: 1  # Defina o número de réplicas conforme necessário
  selector:
    matchLabels:
      app: lissajous
  template:
    metadata:
      labels:
        app: lissajous
    spec:
      containers:
      - name: k8s-lissajous
        image: glaut0n/lissajous-golang:1.1
        ports:
        - name: http-port
          containerPort: 8080  # Porta em que o contêiner escuta
